<?php
/** @var \Bluethinkinc\ProductEnquiry\Block\Product\ListProduct $block */
$product = $block->getProduct();
$pname = $product->getName();
$sku = $product->getSku();
$catproductenquiryenable=$block->productenquirycat();
$Extentionenable=$block->getEndableModule();
$getButtontitle=$block->getButtontitlelistpage();
$gettile=$block->getPopupbuttontilelistpage();
if ($catproductenquiryenable && $Extentionenable):
    ?>
<div>
    <a href="javascript:void(0);" class="enquiry-product"
    data-sku='<?= /* @noEscape */ $sku; ?>' data-title="<?= /* @noEscape */ $gettile; ?>" 
    id="enquiry-product<?= /* @noEscape */ $sku; ?>"><?= /* @noEscape */ $getButtontitle; ?></a>
</div>
<div id="popup-modal<?= /* @noEscape */ $sku; ?>" style="display:none;">
    <div id='responcedata<?= /* @noEscape */ $sku; ?>'></div>
    <div class="formdata" id='formdata<?= /* @noEscape */ $sku; ?>'>
    <input type="hidden" value="<?= /* @noEscape */ $pname; ?>" name='pname' id='pname<?= /* @noEscape */ $sku; ?>'>
    <input type="hidden" value="<?= /* @noEscape */ $sku; ?>" name='sku' 
    id='sku<?= /* @noEscape */ $sku; ?>'>
    <input type="text" value="" name='fname' id='fname<?= /* @noEscape */ $sku; ?>' placeholder="First Name">
    <input type="text" value="" name='lname' id='lname<?= /* @noEscape */ $sku; ?>' placeholder="Last Name">
    <input type="text" value="" name='subject' id='subject<?= /* @noEscape */ $sku; ?>' placeholder="Subject">
    <input type="email" value="" name='email' id='email<?= /* @noEscape */ $sku; ?>' placeholder="Email">
    <textarea placeholder="Message" id="message<?= /* @noEscape */ $sku; ?>"></textarea>
    <span class='Submit_Enquiry_btn' id="submit_enquire<?= /* @noEscape */ $sku; ?>">
    <?= /* @noEscape */ $getButtontitle; ?></span>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
 "*":{"Bluethinkinc_ProductEnquiry/js/productlistenquiry": {}}
}
</script>